/** German copy mirrored from `30Apr26_nexilon-preise.html` (hero through footer). */

export default {
  hero: {
    tag: "Website-Analyse für Deutschschweizer Praxen & Kanzleien",
    h1a: "Die richtige Analyse.",
    h1bEm: "Genau auf Sie zugeschnitten.",
    sub:
      "Kein Einheitsbrei. Starten Sie mit dem kostenlosen Schnell-Check — oder steigen Sie direkt in ein massgeschneidertes Paket ein. Jede Stufe bringt eigenständigen Mehrwert.",
  },
  trust: [
    "Alle Preise in CHF inkl. MWST",
    "Swiss DSG-konform · Daten bleiben in der Schweiz",
    "Für KMU mit 1–20 Mitarbeitenden",
  ],
  ladder: {
    eye: "Stufen 0 – 2",
    title: "Schritt für Schritt zur besseren Website",
    desc: "Die drei Basisstufen bauen aufeinander auf. Jede ist eigenständig buchbar — und jede ist der vollständige nächste Schritt, nicht bloss eine Erweiterung.",
  },
  free: {
    stufe: "Stufe 0 · Kostenlos",
    name: "Schnell-Check",
    desc: "Ihr erster nüchterner Blick auf das, was Ihre Website zurückhält — ohne Aufwand, ohne Kreditkarte.",
    price: "Kostenlos",
    period: "Automatisch · Ergebnis in 6–12 Std.",
    cta: "Kostenlosen Check starten →",
    fgGet: "Was Sie erhalten",
    li1: "Gesamtscore 0–100 mit Einordnung",
    li2: "Top-5-Schwachstellen mit Schweregrad",
    li3: "Branchenvergleich in Ihrer Region",
    li4: "1-Satz-Einschätzung pro Problem",
    liNo: "Lösungen nicht enthalten",
    fgDel: "Lieferung",
    delLi: "6–12 Std. · 1–2 Seiten PDF",
    stufeVar: "Stufe 0 · Kostenlos", // display
  },
  basic: {
    stufeTpl: "Stufe 1 · CHF {price}.–",
    name: "Aktionsbericht",
    desc: "Sie wissen, wo der Schuh drückt. Jetzt erfahren Sie, wie Sie ihn beheben — mit konkreten Schritten, die Sie selbst umsetzen können.",
    periodMain: "Einmalig · 1 Arbeitstag",
    fgPlus: "Alles aus Stufe 0, plus",
    bLi: [
      "Sub-Scores in 5–8 Kategorien",
      "Fix-Empfehlungen für alle Top-5-Probleme",
      "Quick-Wins-Checkliste (8–12 Massnahmen)",
      "Aufwand/Impact-Bewertung pro Fix",
      "3–5 branchenspezifische Insights",
      "DSG / nDSG-Compliance-Hinweise",
    ],
    fgDel: "Lieferung",
    delLi: "1 Arbeitstag · 3–4 Seiten PDF",
    cta: "Aktionsbericht bestellen →",
  },
  advanced: {
    stufeTpl: "Stufe 2 · CHF {price}.–",
    badge: "Empfohlen",
    name: "Professioneller Bericht",
    desc: "Das vollständige Diagnose-Dokument — bereit zur Übergabe an Ihre Agentur oder als Grundlage für die Module B und C.",
    periodMain: "Einmalig · 1–2 Arbeitstage",
    fgPlus: "Alles aus Stufe 1, plus",
    pillFull: "vollständig",
    pillNew: "Neu",
    bLi: [
      "12-Dimensionen-Matrix",
      "Alle 8–15 Probleme vollständig analysiert",
      "Querverweise zwischen Problemen",
      "Wettbewerbskontext in Ihrer Stadt/Ihrem Kanton",
      "Agentur-Briefing-Dokument",
      "Vollständige Branchenanalyse (CH-kalibriert)",
    ],
    fgDel: "Lieferung",
    delLi: "1–2 Arbeitstage · 5–6 Seiten PDF",
    cta: "Professionellen Bericht bestellen →",
  },
  modSection: {
    eyeTpl: "Module B & C — je CHF {price}.–",
    title: "Vertiefen Sie dort, wo es für Sie zählt",
    desc: "Beide Module ergänzen den Professionellen Bericht (Stufe 2) und sind voneinander unabhängig buchbar. Sie wählen, was zu Ihrer Situation passt.",
  },
  modB: {
    badge: "Modul B · Texte & Identität",
    tier: "Identitäts- & Conversion-Suite",
    name: "Ihre Website spricht endlich in Ihrer Sprache",
    desc: "Texte, die den Patienten oder Mandanten dort abholen, wo er steht — und ihn zum nächsten Schritt führen. Fertig zur Implementierung.",
    periodSub: "Add-on zu Stufe 2 · +1 Arbeitstag",
    cta: "Modul B hinzufügen →",
    fg1: "Status-Shift-Analyse (Prompt A)",
    fg1li: [
      "Status-Signal-Diagnose (belegbasiert)",
      "Vollständig umgeschriebene Seite (H1, Abschnitte, CTAs)",
      "Wertversprechen ≤25 Wörter + Vorher/Nachher-Paare",
    ],
    fg2: "5-Winkel-Analyse (Prompt B)",
    fg2li: [
      "3–5 fertige Muster-Testimonials (Schweizer Tonalität)",
      "4–7 Q&A-Paare für die häufigsten Einwände",
      "«Wie es funktioniert»-Block (3–5 Schritte)",
      "Konsolidierter Plug-in-Block (sofort einsetzbar)",
    ],
    fgDel: "Lieferung",
    fgDelli: "+1 Arbeitstag · +3–4 Seiten · vollständig manuell",
  },
  modC: {
    badge: "Modul C · Strategie & Roadmap",
    tier: "Conversion-Booster",
    name: "Ihr strategischer Transformationsplan",
    desc: "8 Phasen. Eine klare Roadmap. CHF-Budgets. Und eine einzige Massnahme, die Sie noch diese Woche umsetzen können.",
    periodSub: "Add-on zu Stufe 2 · +1–2 Arbeitstage",
    cta: "Modul C hinzufügen →",
    fg1: "8-Phasen-Audit (Prompt C)",
    fg1li: [
      "Phasen 1–5: Ziele, Messaging, IA, CTAs, Vertrauen",
      "Phasen 6–8: Performance, Customer Journey, Marke",
      "Min. 2 nicht-offensichtliche Findings 🔍",
    ],
    fg2: "Consulting-Deliverables",
    fg2li: [
      "5-teilige Executive Summary (Urteil, Prioritäten, Outcome)",
      "Roadmap Jetzt / Als Nächstes / Später",
      "CHF-Budgetschätzungen + ROI-Projektion",
      "Impact-Matrix (1 Seite, Entscheidungsgrundlage)",
      "«Massnahme diese Woche» — 1 Schritt, <1 Arbeitstag",
      "Swiss Mode aktiv: CHF, DSG, Hochdeutsch, CH-Hosting",
    ],
    fgDel: "Lieferung",
    fgDelli: "+1–2 Arbeitstage · +5–8 Seiten · Experten-Niveau",
  },
  bundleSection: {
    eye: "Smarte Pakete",
    titleLine1: "Mehr Wirkung.",
    titleLine2: "Besserer Preis.",
    desc: "Kombinieren Sie den Professionellen Bericht mit einem oder beiden Modulen — und profitieren Sie von einem Paketpreis. Jedes Paket ersetzt die Einzelbuchung vollständig.",
  },
  bundle1: {
    badge: "Paket 1 · Diagnose + Text",
    stufe: "Stufe 2 + Modul B",
    name: "Diagnose & Conversion-Texte",
    desc: "Sie erhalten die vollständige Website-Diagnose plus sofort einsetzbare, neu verfasste Texte — kalibriert auf Ihre Zielgruppe in der Deutschschweiz.",
    wasTpl: "Einzeln: CHF {price}.–",
    period: "Einmalig · 2–3 Arbeitstage gesamt",
    saveTpl: "Sie sparen CHF {save}.–",
    cta: "Paket 1 bestellen →",
    fgInc: "Enthalten",
    tags: [
      "✓ Professioneller Bericht (Stufe 2)",
      "✓ Identitäts- & Conversion-Suite (Modul B)",
      "✓ 8–10 Seiten PDF",
      "✓ Texte sofort einsetzbar",
    ],
    fgIdeal: "Ideal für",
    idealLi: ["Praxen, die ihre Texte selbst überarbeiten wollen", "Kanzleien mit bestehendem Webmaster"],
  },
  bundle2: {
    badge: "Paket 2 · Diagnose + Strategie",
    stufe: "Stufe 2 + Modul C",
    name: "Diagnose & Strategie-Roadmap",
    desc: "Die vollständige Diagnose plus einen klaren Transformationsplan — mit CHF-Budgets, ROI-Projektion und einer Massnahme für diese Woche.",
    wasTpl: "Einzeln: CHF {price}.–",
    period: "Einmalig · 2–4 Arbeitstage gesamt",
    saveTpl: "Sie sparen CHF {save}.–",
    cta: "Paket 2 bestellen →",
    fgInc: "Enthalten",
    tags: [
      "✓ Professioneller Bericht (Stufe 2)",
      "✓ Conversion-Booster (Modul C)",
      "✓ 10–14 Seiten PDF",
      "✓ Roadmap + CHF-Budgets",
    ],
    fgIdeal: "Ideal für",
    idealLi: ["Praxen, die eine Agentur briefen möchten", "Kanzleien vor einer Website-Neugestaltung"],
  },
  bundle3: {
    badge: "Bestes Preis-Leistungs-Verhältnis",
    stufe: "Stufe 2 + Modul B + Modul C",
    name: "Das Komplett-Paket",
    desc: "Vollständige Diagnose, überarbeitete Texte und ein strategischer Transformationsplan — alles aus einer Hand, abgestimmt auf Ihre Praxis.",
    wasTpl: "Einzeln: CHF {price}.–",
    period: "Einmalig · 3–5 Arbeitstage gesamt",
    saveTpl: "Sie sparen CHF {save}.–",
    cta: "Komplett-Paket bestellen →",
    fgInc: "Enthalten",
    tags: [
      "✓ Professioneller Bericht (Stufe 2)",
      "✓ Identitäts- & Conversion-Suite (Modul B)",
      "✓ Conversion-Booster (Modul C)",
      "✓ 15–20 Seiten PDF",
      "✓ Texte + Roadmap + CHF-Budgets",
    ],
    fgIdeal: "Ideal für",
    idealLi: [
      "Praxen, die ihre Website ernsthaft transformieren",
      "Kanzleien, die Agentur + Inhalt auf einmal klären",
      "Wer Zeit spart: ein Auftrag statt drei Schritte",
    ],
  },
  comp: {
    eye: "Vollständiger Vergleich",
    title: "Was ist in welcher Stufe enthalten?",
    thFree: "Schnell-Check",
    thFreePrice: "Kostenlos",
    thBasicTpl: "Aktionsbericht",
    thBasicPriceTpl: "CHF {price}",
    thAdvTpl: "Prof. Bericht",
    thAdvPriceTpl: "CHF {price}",
    thModB: "Modul B",
    thModBTpl: "CHF {price}",
    thModC: "Modul C",
    thModCTpl: "CHF {price}",
    groups: {
      kern: "KERN-AUDIT (Prompts 1–11)",
      modB: "MODUL B — IDENTITÄT & CONVERSION-TEXTE (Prompts A+B)",
      modC: "MODUL C — CONVERSION-BOOSTER / STRATEGIE (Prompt C)",
      delivery: "LIEFERUNG",
    },
    rows: {
      rowScore: "Gesamtscore 0–100",
      rowTop5: "Top-5-Schwachstellen",
      rowSub8: "Sub-Scores 5–8 Kategorien",
      rowFix5: "Fix-Empfehlungen Top-5",
      row12Dim: "Vollständige 12-Dimensionen-Matrix",
      rowCompetition: "Wettbewerbskontext Stadt/Kanton",
      rowAgency: "Agentur-Briefing-Dokument",
      rowRewrite: "Vollständig umgeschriebene Seitentexte",
      rowTestimonials: "3–5 fertige Testimonials (CH-Tonalität)",
      rowQA: "4–7 Q&A-Paare (häufigste Einwände)",
      rowPlugin: "Konsolidierter Plug-in-Block",
      rowPhase8: "8-Phasen-Audit + Kausalprotokoll",
      rowRoadmap: "Roadmap Jetzt / Als Nächstes / Später",
      rowBudget: "CHF-Budgetschätzungen + ROI-Projektion",
      rowWeek: "«Massnahme diese Woche»",
      rowSwiss: "Swiss Mode (CHF, DSG, Hochdeutsch)",
      rowPdfPages: "Seiten PDF (ca.)",
      rowLeadTime: "Lieferzeit",
    },
    pdfPages: ["1–2", "3–4", "5–6", "+3–4", "+5–8"],
    leadTimes: ["6–12 Std.", "1 Tag", "1–2 Tage", "+1 Tag", "+1–2 Tage"],
  },
  info: [
    {
      ico: "🔗",
      title: "Module setzen Stufe 2 voraus",
      body: "Die Module B und C bauen auf dem Professionellen Bericht auf. Ein eigenständiger Kauf ohne Stufe 2 ist nicht möglich — sie brauchen das Diagnose-Fundament als Grundlage.",
    },
    {
      ico: "🇨🇭",
      title: "Swiss Mode in jedem Bericht",
      body: "Alle Empfehlungen sind auf CH-Preistransparenz, Swiss DSG/nDSG-Compliance und Deutschschweizer Erwartungen kalibriert. Daten bleiben in der Schweiz. Keine generischen internationalen Empfehlungen.",
    },
    {
      ico: "💼",
      title: "Für wen ist das geeignet?",
      body: "Zahnärztinnen, Ärztepraxen, Physiotherapeutinnen, Psychologinnen, Rechtsanwältinnen, Treuhandbüros, Steuerberaterinnen und andere akademische Fachleute mit 1–20 Mitarbeitenden im Deutschschweizer Raum.",
    },
  ],
  foot: "© JourneyFix.ch · Alle Preise in CHF inkl. MWST · Swiss Made · Daten bleiben in der Schweiz",
} as const;
