/** English copy aligned with `30Apr26_nexilon-preise.html` structure. */

export default {
  hero: {
    tag: "Website analysis for German-speaking Swiss practices & firms",
    h1a: "The right analysis.",
    h1bEm: "Tailored to you.",
    sub:
      "No one-size-fits-all. Start with the free quick scan — or jump straight into a tailored package. Each tier delivers clear standalone value.",
  },
  trust: [
    "All prices in CHF incl. VAT",
    "Swiss FADP-ready · Data stays in Switzerland",
    "For SMEs with 1–20 employees",
  ],
  ladder: {
    eye: "Tiers 0 – 2",
    title: "Step by step to a better website",
    desc: "The three base tiers build on each other. Each can be booked on its own — and each is the full next step, not just an add-on.",
  },
  free: {
    stufe: "Tier 0 · Free",
    name: "Quick scan",
    desc: "Your first clear look at what’s holding your website back — no friction, no credit card.",
    price: "Free",
    period: "Automated · Results in 6–12 hrs",
    cta: "Start free scan →",
    fgGet: "What you get",
    li1: "Overall score 0–100 with context",
    li2: "Top 5 weak points with severity",
    li3: "Industry comparison in your region",
    li4: "One-sentence verdict per issue",
    liNo: "Solutions not included",
    fgDel: "Delivery",
    delLi: "6–12 hrs · 1–2 page PDF",
    stufeVar: "Tier 0 · Free",
  },
  basic: {
    stufeTpl: "Tier 1 · CHF {price}.–",
    name: "Action report",
    desc: "You know where it hurts. Now get how to fix it — with concrete steps you can implement yourself.",
    periodMain: "One-off · 1 business day",
    fgPlus: "Everything in Tier 0, plus",
    bLi: [
      "Sub-scores across 5–8 categories",
      "Fix recommendations for all top-5 issues",
      "Quick-win checklist (8–12 actions)",
      "Effort/impact rating per fix",
      "3–5 industry-specific insights",
      "DSG / nFADP compliance notes",
    ],
    fgDel: "Delivery",
    delLi: "1 business day · 3–4 page PDF",
    cta: "Order action report →",
  },
  advanced: {
    stufeTpl: "Tier 2 · CHF {price}.–",
    badge: "Recommended",
    name: "Professional report",
    desc: "The full diagnostic — ready for your agency or as the foundation for Modules B and C.",
    periodMain: "One-off · 1–2 business days",
    fgPlus: "Everything in Tier 1, plus",
    pillFull: "complete",
    pillNew: "New",
    bLi: [
      "12-dimension matrix",
      "All 8–15 issues fully analysed",
      "Cross-references between issues",
      "Competitive context in your town/canton",
      "Agency briefing document",
      "Full industry analysis (CH-calibrated)",
    ],
    fgDel: "Delivery",
    delLi: "1–2 business days · 5–6 page PDF",
    cta: "Order professional report →",
  },
  modSection: {
    eyeTpl: "Modules B & C · CHF {price}.– each",
    title: "Go deeper where it matters",
    desc: "Both modules extend the Professional Report (Tier 2) and can be booked independently. Pick what fits your situation.",
  },
  modB: {
    badge: "Module B · Copy & identity",
    tier: "Identity & conversion suite",
    name: "Your site finally speaks in your voice",
    desc: "Copy that meets patients or clients where they are — and nudges the next step. Ready to implement.",
    periodSub: "Add-on to Tier 2 · +1 business day",
    cta: "Add module B →",
    fg1: "Status-shift analysis (Prompt A)",
    fg1li: [
      "Status-signal diagnosis (evidence-based)",
      "Fully rewritten page (H1, sections, CTAs)",
      "Value proposition ≤25 words + before/after pairs",
    ],
    fg2: "5-angle analysis (Prompt B)",
    fg2li: [
      "3–5 ready sample testimonials (Swiss tone)",
      "4–7 Q&A pairs for common objections",
      "“How it works” block (3–5 steps)",
      "Consolidated plug-in block (ready to use)",
    ],
    fgDel: "Delivery",
    fgDelli: "+1 business day · +3–4 pages · fully manual",
  },
  modC: {
    badge: "Module C · Strategy & roadmap",
    tier: "Conversion booster",
    name: "Your strategic transformation plan",
    desc: "Eight phases. A clear roadmap. CHF budgets. And one action you can ship this week.",
    periodSub: "Add-on to Tier 2 · +1–2 business days",
    cta: "Add module C →",
    fg1: "8-phase audit (Prompt C)",
    fg1li: [
      "Phases 1–5: goals, messaging, IA, CTAs, trust",
      "Phases 6–8: performance, journey, brand",
      "Min. 2 non-obvious findings 🔍",
    ],
    fg2: "Consulting deliverables",
    fg2li: [
      "5-part executive summary (verdict, priorities, outcome)",
      "Roadmap Now / Next / Later",
      "CHF budget estimates + ROI projection",
      "Impact matrix (one page for decisions)",
      "“Action this week” — one step, <1 business day",
      "Swiss mode on: CHF, DSG, High German, CH hosting",
    ],
    fgDel: "Delivery",
    fgDelli: "+1–2 business days · +5–8 pages · expert level",
  },
  bundleSection: {
    eye: "Smart bundles",
    titleLine1: "More impact.",
    titleLine2: "Better price.",
    desc: "Combine the Professional Report with one or both modules — and benefit from bundle pricing. Each bundle replaces individual purchases.",
  },
  bundle1: {
    badge: "Bundle 1 · Diagnosis + copy",
    stufe: "Tier 2 + Module B",
    name: "Diagnosis & conversion copy",
    desc: "Full website diagnosis plus ready-to-implement rewritten copy — tuned to your audience in German-speaking Switzerland.",
    wasTpl: "Alone: CHF {price}.–",
    period: "One-off · 2–3 business days total",
    saveTpl: "You save CHF {save}.–",
    cta: "Order bundle 1 →",
    fgInc: "Includes",
    tags: [
      "✓ Professional report (Tier 2)",
      "✓ Identity & conversion suite (Module B)",
      "✓ 8–10 page PDF",
      "✓ Copy ready to ship",
    ],
    fgIdeal: "Ideal for",
    idealLi: ["Practices updating copy in-house", "Firms with an existing webmaster"],
  },
  bundle2: {
    badge: "Bundle 2 · Diagnosis + strategy",
    stufe: "Tier 2 + Module C",
    name: "Diagnosis & strategy roadmap",
    desc: "The full diagnostic plus a clear transformation plan — with CHF budgets, ROI projection and one action for this week.",
    wasTpl: "Alone: CHF {price}.–",
    period: "One-off · 2–4 business days total",
    saveTpl: "You save CHF {save}.–",
    cta: "Order bundle 2 →",
    fgInc: "Includes",
    tags: [
      "✓ Professional report (Tier 2)",
      "✓ Conversion booster (Module C)",
      "✓ 10–14 page PDF",
      "✓ Roadmap + CHF budgets",
    ],
    fgIdeal: "Ideal for",
    idealLi: ["Practices briefing an agency", "Firms before a website redesign"],
  },
  bundle3: {
    badge: "Best value",
    stufe: "Tier 2 + Module B + Module C",
    name: "Complete package",
    desc: "Full diagnosis, rewritten copy and a strategic roadmap — one coherent engagement for your practice.",
    wasTpl: "Alone: CHF {price}.–",
    period: "One-off · 3–5 business days total",
    saveTpl: "You save CHF {save}.–",
    cta: "Order complete package →",
    fgInc: "Includes",
    tags: [
      "✓ Professional report (Tier 2)",
      "✓ Identity & conversion suite (Module B)",
      "✓ Conversion booster (Module C)",
      "✓ 15–20 page PDF",
      "✓ Copy + roadmap + CHF budgets",
    ],
    fgIdeal: "Ideal for",
    idealLi: [
      "Practices serious about transforming their site",
      "Firms aligning agency + content in one go",
      "Anyone saving time: one order instead of three steps",
    ],
  },
  comp: {
    eye: "Full comparison",
    title: "What’s included in each tier?",
    thFree: "Quick scan",
    thFreePrice: "Free",
    thBasicTpl: "Action report",
    thBasicPriceTpl: "CHF {price}",
    thAdvTpl: "Prof. report",
    thAdvPriceTpl: "CHF {price}",
    thModB: "Module B",
    thModBTpl: "CHF {price}",
    thModC: "Module C",
    thModCTpl: "CHF {price}",
    groups: {
      kern: "CORE AUDIT (Prompts 1–11)",
      modB: "MODULE B — IDENTITY & CONVERSION COPY (Prompts A+B)",
      modC: "MODULE C — CONVERSION BOOST / STRATEGY (Prompt C)",
      delivery: "DELIVERY",
    },
    rows: {
      rowScore: "Overall score 0–100",
      rowTop5: "Top 5 weak points",
      rowSub8: "Sub-scores 5–8 categories",
      rowFix5: "Fix recommendations (top 5)",
      row12Dim: "Full 12-dimension matrix",
      rowCompetition: "Competitive context (city/canton)",
      rowAgency: "Agency briefing document",
      rowRewrite: "Fully rewritten page copy",
      rowTestimonials: "3–5 ready testimonials (CH tone)",
      rowQA: "4–7 Q&A pairs (common objections)",
      rowPlugin: "Consolidated plug-in block",
      rowPhase8: "8-phase audit + causal log",
      rowRoadmap: "Roadmap Now / Next / Later",
      rowBudget: "CHF budget estimates + ROI projection",
      rowWeek: "“Action this week”",
      rowSwiss: "Swiss mode (CHF, DSG, High German)",
      rowPdfPages: "PDF pages (approx.)",
      rowLeadTime: "Lead time",
    },
    pdfPages: ["1–2", "3–4", "5–6", "+3–4", "+5–8"],
    leadTimes: ["6–12 hrs", "1 day", "1–2 days", "+1 day", "+1–2 days"],
  },
  info: [
    {
      ico: "🔗",
      title: "Modules require Tier 2",
      body: "Modules B and C build on the Professional Report. They can’t be purchased standalone — you need the diagnostic foundation first.",
    },
    {
      ico: "🇨🇭",
      title: "Swiss mode in every report",
      body: "Recommendations are calibrated for CH price transparency, Swiss DSG/nFADP and German-speaking CH expectations. Data stays in Switzerland — no generic global advice.",
    },
    {
      ico: "💼",
      title: "Who is this for?",
      body: "Dentists, medical practices, physios, psychologists, lawyers, fiduciaries, tax advisors and other professional firms with 1–20 staff in German-speaking Switzerland.",
    },
  ],
  foot: "© JourneyFix.ch · All prices in CHF incl. VAT · Swiss made · Data stays in Switzerland",
} as const;
